// SPDX-License-Identifier: BSD-3-Clause
/// Extracts every ```dart fenced code block from the user-facing docs and
/// runs `dart analyze` over them, so documentation snippets cannot silently
/// rot when the API changes.
///
/// How it works:
/// - Snippets are written to [_generatedDir] (gitignored), one file each,
///   annotated with their markdown source location.
/// - Snippets that only contain statements are wrapped in an async function;
///   snippets that declare top-level functions/classes are emitted as-is.
/// - Free identifiers that docs deliberately leave undefined ("your bytes
///   here") are provided by a typed preamble, so member access and named
///   parameters are still fully checked.
/// - Flutter-dependent snippets are skipped: this is a pure Dart package.
library;

import 'dart:io';

import 'package:test/test.dart';

const _docFiles = ['README.md', 'doc/usage_guide.md'];
const _generatedDir = 'test/doc_snippets_generated';

/// Markers for snippets that cannot be analyzed without the Flutter SDK.
const _flutterMarkers = [
  'package:flutter',
  'StatelessWidget',
  'BuildContext',
  'rootBundle',
  'kIsWeb',
];

/// Declarations for free identifiers used by doc snippets. Typed where the
/// type strengthens the check; loose only where the exact type is not what
/// the snippet demonstrates.
const _preamble = '''
late RawActivity activity;
late RawActivity withDistance;
late ActivityLoadResult r;
late ActivityLoadResult result;
late ValidationResult validation;
late Uint8List fitBytes;
late Uint8List sourceBytes;
late String gpxString;
late Object source;
late File someFile;
late EncoderOptions options;
late List<LocationStreamSample> locationStream;
late List<ChannelStreamSample> heartRateStream;
late List<ChannelStreamSample> temperatureStream;
late List<Lap> lapStream;
late Lap lap;
late String withingsCategory;
late Stream<List<int>> largeFileStream;
late DateTime t1;
late DateTime t2;
void log(Object? message) {}
void report(Object? value) {}
void upload(Object? payload) {}
''';

const _header = '''
// GENERATED by doc_snippets_test.dart — do not edit or commit.
// ignore_for_file: unused_local_variable, unused_import, unused_element
// ignore_for_file: avoid_print, prefer_const_constructors
// ignore_for_file: prefer_const_declarations, unnecessary_import
// ignore_for_file: dangling_library_doc_comments, directives_ordering
// ignore_for_file: duplicate_import
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:activity_files/activity_files.dart';
''';

/// Matches column-zero top-level declarations (functions, classes).
final _topLevelDecl = RegExp(r'^(Future<[^;{=]*>|void|class)\s+\w+');

typedef _Snippet = ({String sourceFile, int startLine, String code});

List<_Snippet> _extract(String path) {
  final lines = File(path).readAsLinesSync();
  final snippets = <_Snippet>[];
  var inBlock = false;
  var blockStart = 0;
  final buffer = StringBuffer();
  for (var i = 0; i < lines.length; i++) {
    final trimmed = lines[i].trim();
    if (!inBlock && trimmed == '```dart') {
      inBlock = true;
      blockStart = i + 2; // 1-indexed first line of code
      buffer.clear();
    } else if (inBlock && trimmed == '```') {
      inBlock = false;
      snippets.add((
        sourceFile: path,
        startLine: blockStart,
        code: buffer.toString(),
      ));
    } else if (inBlock) {
      buffer.writeln(lines[i]);
    }
  }
  return snippets;
}

void main() {
  test(
    'all dart snippets in user-facing docs pass analysis',
    () async {
      final dir = Directory(_generatedDir);
      if (dir.existsSync()) dir.deleteSync(recursive: true);
      dir.createSync(recursive: true);

      final origins = <String, String>{};
      var fileIndex = 0;
      for (final doc in _docFiles) {
        for (final snippet in _extract(doc)) {
          if (_flutterMarkers.any(snippet.code.contains)) continue;

          final imports = <String>[];
          final body = <String>[];
          for (final line in snippet.code.split('\n')) {
            (line.startsWith('import ') ? imports : body).add(line);
          }
          final extraImports = imports
              .where((i) => !i.contains('package:activity_files'))
              .join('\n');
          final code = body.join('\n');
          final wrapped = body.any(_topLevelDecl.hasMatch)
              ? code
              : 'Future<void> docSnippetBody() async {\n$code\n}\n';

          final name = 'snippet_${'$fileIndex'.padLeft(2, '0')}.dart';
          origins[name] = '${snippet.sourceFile}:${snippet.startLine}';
          File('${dir.path}/$name').writeAsStringSync(
            '$_header$extraImports\n'
            '// Source: ${origins[name]}\n\n'
            '$_preamble\n'
            '$wrapped',
          );
          fileIndex++;
        }
      }

      expect(
        fileIndex,
        greaterThan(10),
        reason:
            'Snippet extraction found suspiciously few ```dart blocks — '
            'the extraction logic may be broken.',
      );

      final result = await Process.run('dart', ['analyze', dir.path]);
      final output = '${result.stdout}\n${result.stderr}';
      final failingOrigins = origins.entries
          .where((e) => output.contains(e.key))
          .map((e) => '  ${e.key} <- ${e.value}')
          .join('\n');
      expect(
        result.exitCode,
        0,
        reason:
            'Doc snippets failed analysis (generated files kept in '
            '$_generatedDir for inspection):\n$output\n'
            'Failing snippet origins:\n$failingOrigins',
      );

      dir.deleteSync(recursive: true);
    },
    timeout: const Timeout(Duration(minutes: 3)),
  );
}
